name: Zipper

on:
  workflow_dispatch:
    inputs:
      filetozip:
        description: 'File to download and zip'
        required: true


jobs:
  zipFile: 
    runs-on: ubuntu-latest
    steps:
      - name: Download a file
        run: |
          mkdir temp
          cd temp
          curl -LO ${{ github.event.inputs.filetozip }}
          cd -
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r data.zip temp
      - name: Download a file
        run: |
          ls -Ral
      - uses: actions/upload-artifact@v2
        with:
          name: data.zip
