name: Zipper

on:
  workflow_dispatch:
    inputs:
      filetozip:
        description: 'File to download and zip'
        required: true


jobs:
  zipFile: 
    runs-on: ubuntu-latest
    steps:
      - name: Download a file
        run: |
          mkdir temp
          cd temp
          curl -LO ${{ github.event.inputs.filetozip }}
          cd -
      - name: Debug
        run: |
          ls -Ral
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: temp